name: jobs 

on: 
  push:
    branches:
      - master
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: pritingitn the variable
        run: |
          echo "this is sucessfule"



